[tool.poetry]
name = "realtime-webchat-back"
version = "0.1.0"
description = ""
authors = ["gahyuun <pgh123166@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
